# Generated by Django 4.0.3 on 2022-03-11 13:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('1', 'Core'), ('2', 'Specialization')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Program',
            fields=[
                ('deg_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('deg_program_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('prof_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_initial', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)])),
                ('sem_initial', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', 'Midyear')], default='1', max_length=1)),
                ('years_to_grad', models.IntegerField()),
                ('study_plan', models.CharField(choices=[('1', 'Full-time'), ('2', 'Part-time'), ('3', 'Non-Degree')], default='1', max_length=1)),
                ('adviser_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.professor')),
                ('curr_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='current_spec', to='gspt_test.specialization')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.lab')),
                ('prev_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prev_spec', to='gspt_test.specialization')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.degree_program')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course', to='gspt_test.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('remark', models.CharField(blank=True, choices=[('1', 'pass'), ('2', 'inc'), ('3', 'drp')], max_length=1, null=True)),
                ('sem', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', 'Midyear')], default='1', max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.course')),
                ('student_no', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.lab'),
        ),
    ]
