# Generated by Django 4.0.3 on 2022-03-30 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gspt_test', '0002_coreq_prereq_delete_pre_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_initial', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)])),
                ('sem_initial', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', 'Midyear')], default='1', max_length=1)),
                ('years_to_grad', models.IntegerField()),
                ('is_professor', models.BooleanField()),
                ('study_plan', models.CharField(choices=[('1', 'Full-time'), ('2', 'Part-time'), ('3', 'Non-Degree')], default='1', max_length=1)),
                ('gwa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('units_taken', models.DecimalField(decimal_places=1, max_digits=4)),
                ('units_required', models.DecimalField(decimal_places=1, max_digits=4)),
                ('adviser_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.person')),
                ('curr_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='current_spec', to='gspt_test.specialization')),
                ('deg_program_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.degree_program')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.lab')),
                ('prev_spec_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prev_spec', to='gspt_test.specialization')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='adviser_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='curr_spec_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lab_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prev_spec_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='program_id',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gspt_test.person'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
