# Generated by Django 4.0.3 on 2022-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspt_test', '0006_alter_person_adviser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('1', 'Core'), ('2', 'Specialization'), ('3', 'Elective')], max_length=1),
        ),
    ]
