# Generated by Django 4.0.3 on 2022-05-01 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspt_test', '0007_alter_course_course_id_alter_course_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='year',
            field=models.IntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='remark',
            field=models.CharField(blank=True, choices=[('1', 'Pass'), ('2', 'INC'), ('3', 'DRP')], max_length=1, null=True),
        ),
    ]
