# Generated by Django 4.0.3 on 2022-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gspt_test', '0008_enrollment_year_alter_enrollment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
